# Generated by Django 5.0.6 on 2024-06-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.passage'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, default='A0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, default='A0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, default='A0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, default='A0', max_length=5, null=True),
        ),
    ]
